base_url = "https://www.aeraglyx.com"

taxonomies = [
    { name = "tags", feed = true, render = true},
]

[extra]
nav = [
    { name = "blog", url = "/blog/" },
    { name = "work", url = "/blog/" },
    { name = "links", url = "/blog/" },
]
