base_url = "https://www.aeraglyx.com"

title = "Aeraglyx"
description = "VFX Artist | Technical Director | Recreational Programmer"

taxonomies = [
    { name = "tags", feed = true, render = true},
]

[extra]
nav = [
    { name = "blog", url = "/blog/" },
    { name = "vfx", url = "/vfx/" },
]
links = [
    { name = "github", url = "https://github.com/aeraglyx" },
    { name = "twitter", url = "https://x.com/aeraglyx" },
    { name = "linkedin", url = "https://www.linkedin.com/in/aeraglyx/" },
]
